In [1]:
import numpy as np
import Orange
import os

In [2]:
a = np.array([2, 3, 5, 5, 5])

In [3]:
np.unique(a)

array([2, 3, 5])

In [4]:
import pandas as pd
df = pd.read_csv("ionosphere.csv", header=None)
display(df)

X = df.drop(34, axis=1).values
print(type(X))
display(X)

y = np.array([1 if u == 'g' else 0 for u in df[34].values])
print(type(y))
display(y)

0   1        2        3        4        5        6        7        8   \
0     1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..   ..  ..      ...      ...      ...      ...      ...      ...      ...   
346   1   0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347   1   0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348   1   0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349   1   0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350   1   0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

          9   ...       25       26       27       28       29       30  \
0    0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1   -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2    0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3    0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4   -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   
..       ...  ...      ...      ...      ...      ...      ...      ...   
346 -0.04622  ... -0.04202  0.83479  0.00123  1.00000  0.12815  0.86660   
347  0.01606  ...  0.01361  0.93522  0.04925  0.93159  0.08168  0.94066   
348  0.02446  ...  0.03193  0.92489  0.02542  0.92120  0.02242  0.92459   
349  0.00110  ... -0.02099  0.89147 -0.07760  0.82983 -0.17238  0.96022   
350 -0.09139  ... -0.15114  0.81147 -0.04822  0.78207 -0.00703  0.75747   

          31       32       33  34  
0   -0.54487  0.18641 -0.45300   g  
1   -0.06288 -0.13738 -0.02447   b  
2   -0.24180  0.56045 -0.38238   g  
3    1.00000 -0.32382  1.00000   b  
4   -0.59573 -0.04608 -0.65697   g  
..       ...      ...      ...  ..  
346 -0.10714  0.90546 -0.04307   g  
347 -0.00035  0.91483  0.04712   g  
348  0.00442  0.92697 -0.00577   g  
349 -0.03757  0.87403 -0.16243   g  
350 -0.06678  0.85764 -0.06151   g  

[351 rows x 35 columns]

<class 'numpy.ndarray'>


array([[ 1.     ,  0.     ,  0.99539, ..., -0.54487,  0.18641, -0.453  ],
       [ 1.     ,  0.     ,  1.     , ..., -0.06288, -0.13738, -0.02447],
       [ 1.     ,  0.     ,  1.     , ..., -0.2418 ,  0.56045, -0.38238],
       ...,
       [ 1.     ,  0.     ,  0.94701, ...,  0.00442,  0.92697, -0.00577],
       [ 1.     ,  0.     ,  0.90608, ..., -0.03757,  0.87403, -0.16243],
       [ 1.     ,  0.     ,  0.8471 , ..., -0.06678,  0.85764, -0.06151]])

<class 'numpy.ndarray'>


array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [5]:
from IMLI import IMLI

imli = IMLI(n_clauses=2, lamda=1, solver="open-wbo", n_partitions=1, rule_type="DNF", timeout=120)
features = imli.generate_features(X, y, categorical_features_id=[], discretizer="entropy")

In [6]:
for feature in features:
    print(feature.feature_type)

raw_binary
raw_categorical
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous
raw_continuous


In [7]:
imli.fit(X, y, features)

In [8]:
imli._preprocess(X)

(array([[1., 0., 1., ..., 1., 1., 1.],
        [1., 0., 1., ..., 1., 1., 1.],
        [1., 0., 1., ..., 1., 1., 1.],
        ...,
        [1., 0., 1., ..., 1., 1., 1.],
        [1., 0., 1., ..., 1., 1., 1.],
        [1., 0., 1., ..., 1., 1., 1.]]),
  <IMLI.DiscretizedFeature at 0x7f342c2e3eb8>])

In [9]:
print(len(imli.new_features))
for feature in imli.new_features:
    print(feature, feature.negation())

222
X0 (NOT X0)
(NOT X0) X0
X2 >= 0.190280 X2 < 0.190280
X2 >= 0.739470 X2 < 0.739470
X2 >= 0.998505 X2 < 0.998505
X2 < 0.190280 X2 >= 0.190280
X2 < 0.739470 X2 >= 0.739470
X2 < 0.998505 X2 >= 0.998505
X3 >= -0.609635 X3 < -0.609635
X3 >= -0.000170 X3 < -0.000170
X3 >= 0.007075 X3 < 0.007075
X3 >= 0.746850 X3 < 0.746850
X3 < -0.609635 X3 >= -0.609635
X3 < -0.000170 X3 >= -0.000170
X3 < 0.007075 X3 >= 0.007075
X3 < 0.746850 X3 >= 0.746850
X4 >= 0.041440 X4 < 0.041440
X4 >= 0.418075 X4 < 0.418075
X4 >= 0.995175 X4 < 0.995175
X4 < 0.041440 X4 >= 0.041440
X4 < 0.418075 X4 >= 0.418075
X4 < 0.995175 X4 >= 0.995175
X5 >= -0.795310 X5 < -0.795310
X5 >= -0.217515 X5 < -0.217515
X5 >= -0.000715 X5 < -0.000715
X5 >= 0.001010 X5 < 0.001010
X5 >= 0.825090 X5 < 0.825090
X5 < -0.795310 X5 >= -0.795310
X5 < -0.217515 X5 >= -0.217515
X5 < -0.000715 X5 >= -0.000715
X5 < 0.001010 X5 >= 0.001010
X5 < 0.825090 X5 >= 0.825090
X6 >= 0.029375 X6 < 0.029375
X6 >= 0.999995 X6 < 0.999995
X6 < 0.029375 X6 >= 0.02

In [10]:
imli.get_rule()

'[X0 AND X2 >= 0.739470 AND X4 >= 0.041440 AND X7 >= -0.983575] OR [X0 AND X2 >= 0.190280 AND X5 >= -0.217515 AND X9 >= -0.572990 AND X13 >= -0.554585 AND X15 < 0.968410 AND X18 >= -0.989535 AND X27 >= -0.936175 AND X28 >= 0.067790 AND X33 >= 0.005400]'

In [11]:
preds = imli.predict(X)

In [12]:
from sklearn.metrics import classification_report

print(classification_report(y, preds))

              precision    recall  f1-score   support

           0       0.81      0.92      0.86       126
           1       0.95      0.88      0.91       225

    accuracy                           0.89       351
   macro avg       0.88      0.90      0.89       351
weighted avg       0.90      0.89      0.89       351

