In [1]:
import numpy as np
import Orange
import os

In [2]:
a = np.array([2, 3, 5, 5, 5])

In [3]:
np.unique(a)

array([2, 3, 5])

In [4]:
import pandas as pd
df = pd.read_csv("test-multiple-features.csv")
display(df)

X = df.drop('y', axis=1).values
print(type(X))
display(X)

y = df['y'].values
print(type(y))
display(y)

x1  x2  x3  x4  y
0  1.5   0   5   1  1
1  1.0   0   6   0  1
2  0.0   0   7   1  0
3  0.0   1   7   1  0

<class 'numpy.ndarray'>


array([[1.5, 0. , 5. , 1. ],
       [1. , 0. , 6. , 0. ],
       [0. , 0. , 7. , 1. ],
       [0. , 1. , 7. , 1. ]])

<class 'numpy.ndarray'>


array([1, 1, 0, 0])

In [5]:
from IMLI import IMLI

imli = IMLI(n_clauses=2, lamda=1, solver="open-wbo", n_partitions=1, rule_type="DNF")
features = imli.generate_features(X, y, categorical_features_id=[3], discretizer="entropy")

In [6]:
for feature in features:
    print(feature.feature_type)

raw_continuous
raw_binary
raw_continuous
raw_categorical


In [7]:
imli.fit(X, y, features)

In [8]:
imli._preprocess(X)

(array([[1., 0., 0., 1., 0., 1., 0., 1., 1., 0.],
        [1., 0., 0., 1., 0., 1., 1., 0., 0., 1.],
        [0., 1., 0., 1., 1., 0., 0., 1., 1., 0.],
        [0., 1., 1., 0., 1., 0., 0., 1., 1., 0.]]),
  <IMLI.CategoricalFeature at 0x7f5850bb5b00>])

In [9]:
for feature in imli.new_features:
    print(feature, feature.negation())

X0 >= 0.500000 X0 < 0.500000
X0 < 0.500000 X0 >= 0.500000
X1 (NOT X1)
(NOT X1) X1
X2 >= 6.500000 X2 < 6.500000
X2 < 6.500000 X2 >= 6.500000
X3 == 0.000000 X3 != 0.000000
X3 == 1.000000 X3 != 1.000000
X3 != 0.000000 X3 == 0.000000
X3 != 1.000000 X3 == 1.000000


In [10]:
imli.get_rule()

'[X0 >= 0.500000] OR [X0 >= 0.500000]'

In [11]:
imli.predict(X)

array([1, 1, 0, 0])