In [1]:
import sys
sys.path.insert(1, '../')

import pandas as pd
import numpy as np
from IMLI import IMLI

In [2]:
DATASET_NAME = "liver"

In [3]:
df_total = pd.read_csv(("%s/holdout/%s.csv" % (DATASET_NAME, DATASET_NAME)))
display(df_total.tail())

0  1    2    3    4   5   6    7    8     9  10
574  60  1  0.5  0.1  500  20  34  5.9  1.6  0.37   0
575  40  1  0.6  0.1   98  35  31  6.0  3.2  1.10   1
576  52  1  0.8  0.2  245  48  49  6.4  3.2  1.00   1
577  31  1  1.3  0.5  184  29  32  6.8  3.4  1.00   1
578  38  1  1.0  0.3  216  21  24  7.3  4.4  1.50   0

In [4]:
# df_total[df_total['1'] < 4.5][df_total['2'] >= 1125][df_total['4'] == 1].shape

In [5]:
df_total_np = df_total.values
X_total = df_total_np[:, :-1]
y_total = df_total_np[:, -1]

In [6]:
features = IMLI().generate_features(
        X_total,
        y_total,
        categorical_features_id=[],
        discretizer="entropy",
#         n_thresholds=9
    )

In [9]:
model = IMLI()
model.fit(X_total[:20], y_total[:20], features)

In [10]:
new_X, features = model._preprocess(X_total)

In [11]:
for f in features:
    print(f)

X1
(NOT X1)
X2 >= 1.650000
X2 < 1.650000
X3 >= 1.250000
X3 < 1.250000
X4 >= 211.500000
X4 < 211.500000
X5 >= 61.500000
X5 < 61.500000
X6 >= 59.500000
X6 < 59.500000
X9 >= 0.895000
X9 < 0.895000


In [12]:
display(new_X[y_total == 1])

array([[0., 1., 0., ..., 1., 1., 0.],
       [1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [15]:
unique, counts = np.unique(new_X[y_total == 0], axis=0, return_counts=True)
for i, u in enumerate(unique):
    print(u, counts[i])
    
print(len(unique))

[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.] 5
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0.] 31
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1.] 1
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0.] 1
[0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.] 1
[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.] 3
[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.] 3
[0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.] 3
[1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.] 13
[1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0.] 52
[1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0.] 6
[1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1.] 2
[1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.] 1
[1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.] 7
[1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.] 13
[1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0.] 3
[1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.] 2
[1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.] 2
[1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0.] 2
[1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0.] 1
[1. 0. 1. 0. 0. 1. 0. 1. 1. 0.

In [16]:
unique, counts = np.unique(new_X[y_total == 1], axis=0, return_counts=True)
for i, u in enumerate(unique):
    print(u, counts[i])
    
print(len(unique))

[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.] 10
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0.] 28
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0.] 1
[0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.] 1
[0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.] 2
[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.] 5
[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.] 8
[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1.] 1
[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0.] 1
[0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1.] 6
[0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.] 2
[0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.] 2
[0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1.] 2
[0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0.] 2
[0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1.] 2
[0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0

In [17]:
unique, counts = np.unique(new_X, axis=0, return_counts=True)
for i, u in enumerate(unique):
    print(u, counts[i])
    
print(len(unique))

[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.] 15
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0.] 59
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1.] 1
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0.] 2
[0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.] 2
[0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.] 2
[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.] 8
[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.] 11
[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1.] 1
[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0.] 1
[0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1.] 6
[0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.] 3
[0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.] 4
[0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1.] 1
[0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.] 2
[0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1.] 2
[0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0.] 2
[0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 